dist: bionic
language: python
python:
  - "3.6"
  - "3.5"

before_install:
  - sudo apt-get update
  - sudo apt-get -y install gobject-introspection
  - sudo apt-get -y install libgirepository1.0-dev

# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install -e .

script:
  - pytest
