dist: bionic
language: python
python:
  - "3.8"
  - "3.7"
  - "3.6"
  - "3.5"
  
# command to install dependencies
install:
  - pip install -e .
  - pip install -r requirements.txt

script:
  - echo "Hello World"
