dist: bionic
language: python
python:
  - "3.6"
  - "3.5"

before_install:
  - sudo apt-get update
  - sudo apt-get -y install gobject-introspection-1.0

# command to install dependencies
install:
  - pip install -e .
  - pip install -r requirements.txt

script:
  - pytest
