dist: bionic
language: python
python:
  - "3.6"
  - "3.5"

before_install:
  - sudo apt-get update
  - sudo apt-get -y install python3-gi gobject-introspection gir1.2-gtk-3.0
  - sudo apt-get -y install libgirepository1.0-dev

# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install -e .

script:
  - pytest
  - python trackmanagementsystem/__main__.py
